---
dnf_packages:
  - neofetch
  - python3-psutil
  - dconf
  - dbus-tools
  - dbus-daemon
  - htop

flatpak_packages:
  - com.visualstudio.code
  - com.axosoft.GitKraken
  - rest.insomnia.Insomnia

rpm_packages:
  - "https://github.com/vercel/hyper/releases/download/v3.3.0/hyper-3.3.0.x86_64.rpm"

# Nerd fonts
nf_single_fonts:
  - "Inconsolata/complete/Inconsolata Regular Nerd Font Complete.ttf"
  - "SourceCodePro/Regular/complete/Sauce Code Pro Nerd Font Complete.ttf"
  - "FiraCode/Regular/complete/Fira Code Regular Nerd Font Complete.ttf"

nf_user: "{{ lookup('env', 'USER') }}"

# zsh
zsh_aliases:
  - { alias: "code", action: "flatpak run com.visualstudio.code" }
zsh_antigen_bundles_extras:
  - git
  - nvm
  - tomsquest/nvm-auto-use.zsh
zsh_antigen_theme: agnoster
zsh_custom_after: 'eval "$(starship init zsh)"'

# nvm
nvm_profile: "{{ansible_env.HOME}}/.zshrc.local"
nvm_dir: "{{ansible_env.HOME}}/.nvm"
nvm_install: "git"
nvm_version: "0.39.2"

# dotfiles
dotfiles_repo: "git@github.com:talvor/dotfiles.git"
dotfiles_repo_version: master

# hyperjs
hyperjs_version: "3.3.0"
