---
dnf_packages:
  - neofetch
  - python3-psutil
  - dconf
  - dbus-tools
  - dbus-daemon
  - htop
  - podman
  - alacritty

flatpak_packages:
  - com.visualstudio.code
  - com.axosoft.GitKraken

# Nerd fonts
nf_single_fonts:
  - "Inconsolata/complete/Inconsolata Regular Nerd Font Complete.ttf"
  - "SourceCodePro/Regular/complete/Sauce Code Pro Nerd Font Complete.ttf"
  - "FiraCode/Regular/complete/Fira Code Regular Nerd Font Complete.ttf"

nf_user: "{{ lookup('env', 'USER') }}"

# zsh
zsh_aliases:
  - { alias: "docker", action: "podman" }
  - { alias: "code", action: "flatpak run com.visualstudio.code" }
zsh_antigen_bundles_extras:
  - git
  - nvm
zsh_antigen_theme: agnoster
zsh_custom_after: 'eval "$(starship init zsh)"'

# nvm
nvm_profile: "{{ansible_env.HOME}}/.zshrc.local"
nvm_dir: "{{ansible_env.HOME}}/.nvm"
nvm_install: "git"
nvm_version: "0.39.2"

# dotfiles
dotfiles_repo: "https://github.com/talvor/dotfiles.git"
dotfiles_repo_version: master
