---
- hosts: all

  vars_files:
    - default.config.yml

  vars:
    home: "{{ lookup('env', 'HOME') }}"

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: ctorgalson.nerdfonts
      tags: ["font"]

    - role: andrewrothstein.starship
      tags: ["zsh"]

    - role: talvor.ansible-role-zsh
      zsh_user: "{{ lookup('env', 'USER') }}"
      tags: ["zsh"]

    - role: talvor.ansible-role-nvm
      tags: ["nvm"]

    - role: talvor.ansible-role-dotfiles
      tags: ["dotfiles"]

  tasks:
    - import_tasks: tasks/dnf-packages.yml
      tags: ["dnf-packages"]

    - import_tasks: tasks/flatpak-packages.yml
      tags: ["flatpak-packages"]

    - import_tasks: tasks/development.yml
      tags: ["development"]
