---
- name: Install dnf packages.
  ansible.builtin.package:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ dnf_packages }}"
  become: true

