---
- name: Converge
  hosts: all
  vars:
    nf_user: "molecule"
    nf_group: "molecule"
    nf_single_fonts:
     - "UbuntuMono/Regular/complete/Ubuntu Mono Nerd Font Complete.ttf"
     - "AurulentSansMono/complete/AurulentSansMono-Regular Nerd Font Complete.otf"
  tasks:
    - name: "Include ansible-role-nerdfonts"
      include_role:
        name: "ansible-role-nerdfonts"
